global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
      monitor: 'wealthsystems-monitoring'

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:

  - job_name: 'Prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - 'prometheus:9090'
  
  - job_name: 'node-exporter'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    dns_sd_configs:
    - names:
      - node-exporter
      refresh_interval: 15s
      type: A
      port: 9100

  - job_name: 'cadvisor'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    dns_sd_configs:
    - names:
      - cadvisor
      refresh_interval: 15s
      type: A
      port: 8080
      